---
deployment:
  tasks:
    - export DEPLOYPATH=/home/greentwi/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R about.html $DEPLOYPATH
    - /bin/cp -R contact.html $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R sustainability.html $DEPLOYPATH
    